
/* Drop Tables */

--DROP TABLE COMMENTS CASCADE CONSTRAINTS;
--DROP TABLE BBS CASCADE CONSTRAINTS;
--DROP TABLE MEMBER CASCADE CONSTRAINTS;



/* Drop Sequences */

--DROP SEQUENCE SEQ_BBS;
--DROP SEQUENCE SEQ_COMM;




/* Create Sequences */

CREATE SEQUENCE SEQ_BBS NOCYCLE NOCACHE;
CREATE SEQUENCE SEQ_COMM NOCYCLE NOCACHE;



/* Create Tables */

CREATE TABLE BBS
(
	NO NUMBER NOT NULL,
	ID varchar2(10 char),
	TITLE nvarchar2(50) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	TRIP nvarchar2(20) NOT NULL,
	VISITCOUNT  DEFAULT 0,
	POSTDATE date DEFAULT SYSDATE
,
	CONSTRAINT SYS_C007113 PRIMARY KEY (NO)
);


CREATE TABLE COMMENTS
(
	COMMENTSNO number NOT NULL,
	ID varchar2(10 char),
	NO NUMBER,
	COMMENTS nvarchar2(100) NOT NULL,
	REGIDATE date DEFAULT sysdate,
	CONSTRAINT SYS_C007132 PRIMARY KEY (COMMENTSNO)
);


CREATE TABLE MEMBER
(
	ID varchar2(10 char) NOT NULL,
	PASSWORD varchar2(10 char) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	GENDER nvarchar2(10),
	INTER nvarchar2(10),
	GRADE nvarchar2(10),
	INTRO nvarchar2(500),
	REGIDATE date DEFAULT sysdate,
	CONSTRAINT SYS_C007101 PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE COMMENTS
	ADD CONSTRAINT SYS_C007134 FOREIGN KEY (NO)
	REFERENCES BBS (NO)
;


ALTER TABLE BBS
	ADD CONSTRAINT SYS_C007114 FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE COMMENTS
	ADD CONSTRAINT SYS_C007133 FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;



